language: node_js
node_js:
  - "10.11.0"

deploy:
  provider: heroku
  api_key:
    secure: "a97e9c63-6a62-4ce7-8b11-cf835d1a2a92"
  app:
    develop: devopstest-staging
    master: devopstest-staging